services:
  redis:
    container_name: 'gaio-redis'
    image: redis
    hostname: 'redis'
    command: redis-server --save "" --appendonly no --maxclients 20000
    ports:
      - 6379:6379
    restart: always
    networks:
      - gaio-network
  app:
    container_name: 'gaio-dataos'
    build: .
    command: bun run dev
    x-develop:
      watch:
        - action: sync
          path: ./web
          target: /src/web
          ignore: 
            - node_modules
        - action: rebuild
          path: package.json
    environment:
      GAIO_REDIS_HOST: redis
    ports:
      - 3000:3000
      - 5173:5173
    volumes:
      - .:/usr/app
    depends_on:
      - redis
    networks:
      - gaio-network

networks:
  gaio-network:
    driver: bridge