export const executables = [
    'builder',
    'pca',
    'insert',
    'pivot',
    'query',
    'fileImport',
    'export',
    'scoring',
    'paramToTable',
    'tableToParam',
    'rest',
    'whatsapp',
    'r',
    'mail',
    'flow',
    'automl',
    'userMirror',
    'castData',
    'update',
    'delete',
    'insertRow',
    'create',
    'timeseries',
    'sourceRaw',
    'basket',
    'cluster',
    'coxph',
    'sample',
    'externalOutput',
    'csvUrl',
    'unpivot',
    'cloudStorage',
    'googleSpreadsheet',
    'scorecard',
    'nodeEdge',
    'nodeEdgeFilter',
    'localCsv',
    'python'
]

export const reports = ['form', 'report', 'maps', 'network', 'powerSearch', 'scorecard']

export const typesOfOpenTask = [
    'localCsv',
    'pca',
    'coxph',
    'sourceRaw',
    'timeseries',
    'basket',
    'cluster',
    'castData',
    'automl',
    'insert',
    'export',
    'scoring',
    'api',
    'rest',
    'whatsapp',
    'paramToTable',
    'tableToParam',
    'pivot',
    'mail',
    'r',
    'userMirror',
    'flow',
    'update',
    'insertRow',
    'delete',
    'create',
    'sample',
    'externalOutput',
    'csvUrl',
    'googleSpreadsheet',
    'unpivot',
    'cloudStorage',
    'network',
    'powerSearch',
    'scorecard',
    'nodeEdge',
    'nodeEdgeFilter',
    'python'
]

export const taskList = (t: Function) => {
    return [
        {
            title: `${t('taskBuilder')}`,
            type: 'builder',
            onlyBucket: true,
            icon: 'builder',
            cat: 'DATAPREP',
            catIcon: '',
            contextOrder: 1,
            showOnContextMenu: true,
            order: 1
        },
        {
            title: `${t('taskSql')}`,
            type: 'query',
            onlyBucket: false,
            icon: 'add',
            cat: 'DATAPREP',
            catIcon: '',
            contextOrder: 100,
            showOnContextMenu: true,
            order: 1
        },
        {
            title: `${t('taskSourceSql')}`,
            type: 'sourceRaw',
            onlyBucket: false,
            icon: 'table',
            cat: 'DATAPREP',
            catIcon: '',
            contextOrder: 100,
            showOnContextMenu: true,
            order: 1
        },
        {
            title: `${t('taskExplorer')}`,
            type: 'report',
            onlyBucket: true,
            onlyRepo: true,
            icon: 'g-report',
            cat: 'DELIVERY',
            catIcon: '',
            showOnContextMenu: true,
            contextOrder: 2,
            order: 3
        },
        // {
        //     title: `${t('taskPowerSearch')}`,
        //     type: 'powerSearch',
        //     onlyBucket: true,
        //     onlyRepo: false,
        //     icon: 'g-power-search',
        //     cat: 'DELIVERY',
        //     catIcon: '',
        //     showOnContextMenu: true,
        //     contextOrder: 3,
        //     order: 3
        // },
        {
            title: `${t('taskNetworkExplorer')}`,
            type: 'network',
            onlyBucket: false,
            hidden: true,
            onlyRepo: false,
            icon: 'g-network',
            cat: 'DELIVERY',
            catIcon: '',
            showOnContextMenu: true,
            contextOrder: 10,
            order: 10
        },
        {
            title: `${t('taskInsertTable')}`,
            type: 'insert',
            onlyBucket: true,
            icon: 'g-union-table',
            cat: 'DATAPREP',
            catIcon: '',
            showOnContextMenu: true,
            contextOrder: 100,
            order: 1
        },
        {
            title: `${t('taskInsertRow')}`,
            type: 'insertRow',
            onlyBucket: false,
            icon: 'g-row-insert',
            cat: 'DATAPREP',
            catIcon: '',
            showOnContextMenu: true,
            contextOrder: 100,
            order: 1
        },
        {
            title: `${t('taskUpdateTable')}`,
            type: 'update',
            onlyBucket: false,
            icon: 'g-table-update',
            cat: 'DATAPREP',
            catIcon: '',
            showOnContextMenu: true,
            contextOrder: 100,
            order: 1
        },
        {
            title: `${t('taskDeleteTable')}`,
            type: 'delete',
            onlyBucket: false,
            icon: 'g-row-exclude',
            cat: 'DATAPREP',
            catIcon: '',
            showOnContextMenu: true,
            contextOrder: 100,
            order: 1
        },
        {
            title: `${t('taskCreateTable')}`,
            type: 'create',
            onlyBucket: false,
            icon: 'g-create-table',
            cat: 'DATAPREP',
            catIcon: '',
            contextOrder: 100,
            showOnContextMenu: true,
            order: 1
        },
        {
            title: `${t('taskQuickTable')}`,
            type: 'quickTable',
            onlyBucket: false,
            icon: 'g-quick-table',
            cat: 'DATAPREP',
            catIcon: '',
            contextOrder: 100,
            showOnContextMenu: true,
            order: 1
        },
        {
            title: `${t('taskSample')}`,
            type: 'sample',
            onlyBucket: true,
            icon: 'g-sample',
            cat: 'ANALYTICS',
            showOnContextMenu: true,
            catIcon: '',
            contextOrder: 100,
            order: 2
        },
        {
            title: `${t('taskStaticContent')}`,
            type: 'staticContent',
            onlyBucket: false,
            icon: 'g-content',
            hidden: false,
            cat: 'DELIVERY',
            catIcon: '',
            contextOrder: 100,
            showOnContextMenu: true,
            order: 3
        },
        {
            title: `${t('taskForms')}`,
            type: 'form',
            onlyBucket: false,
            icon: 'g-forms',
            cat: 'DELIVERY',
            catIcon: '',
            contextOrder: 100,
            showOnContextMenu: true,
            order: 3
        },
        {
            title: `${t('taskExternalOutput')}`,
            type: 'externalOutput',
            onlyBucket: true,
            icon: 'g-external-output',
            cat: 'DELIVERY',
            catIcon: '',
            showOnContextMenu: true,
            contextOrder: 100,
            order: 3
        },
        {
            title: `${t('taskPivot')}`,
            type: 'pivot',
            onlyBucket: true,
            icon: 'g-pivot-table',
            cat: 'DATAPREP',
            catIcon: '',
            showOnContextMenu: true,
            contextOrder: 100,
            order: 1
        },
        {
            title: `${t('taskUnpivot')}`,
            type: 'unpivot',
            onlyBucket: true,
            icon: 'g-unpivot',
            hidden: false,
            cat: 'DATAPREP',
            catIcon: '',
            showOnContextMenu: true,
            contextOrder: 100,
            order: 1
        },
        {
            title: `${t('taskBanner')}`,
            hidden: true,
            type: 'banner',
            onlyBucket: false,
            icon: 'g-banner',
            cat: 'DELIVERY',
            catIcon: '',
            contextOrder: 100,
            showOnContextMenu: true,
            order: 3
        },
        {
            title: `${t('taskExportFile')}`,
            type: 'export',
            onlyBucket: true,
            icon: 'g-export-csv',
            cat: 'DELIVERY',
            showOnContextMenu: true,
            catIcon: '',
            contextOrder: 3,
            order: 3
        },
        {
            title: `${t('taskAutoml')}`,
            type: 'automl',
            onlyBucket: false,
            icon: 'g-automl',
            showOnContextMenu: true,
            cat: 'ANALYTICS',
            catIcon: '',
            contextOrder: 3,
            order: 2
        },
        {
            title: `${t('taskScoring')}`,
            type: 'scoring',
            onlyBucket: false,
            icon: 'g-scoring',
            cat: 'ANALYTICS',
            catIcon: '',
            showOnContextMenu: true,
            contextOrder: 100,
            order: 2
        },
        {
            title: `${t('taskSurvivorAnalytics')}`,
            type: 'coxph',
            onlyBucket: true,
            icon: 'linechart-decline',
            hidden: true,
            cat: 'DELIVERY',
            showOnContextMenu: true,
            catIcon: '',
            contextOrder: 100,
            order: 3
        },
        {
            title: `${t('taskCluster')}`,
            type: 'cluster',
            onlyBucket: true,
            icon: 'g-cluster',
            showOnContextMenu: true,
            cat: 'ANALYTICS',
            catIcon: '',
            contextOrder: 100,
            order: 2
        },
        {
            title: `${t('taskPca')}`,
            type: 'pca',
            onlyBucket: true,
            icon: 'g-pca',
            cat: 'ANALYTICS',
            catIcon: '',
            showOnContextMenu: true,
            contextOrder: 100,
            order: 2
        },
        {
            title: `${t('taskBasket')}`,
            type: 'basket',
            onlyBucket: true,
            icon: 'g-association-rules',
            cat: 'ANALYTICS',
            showOnContextMenu: true,
            catIcon: '',
            contextOrder: 100,
            order: 2
        },
        {
            title: `${t('taskTimeSeries')}`,
            type: 'timeseries',
            onlyBucket: true,
            showOnContextMenu: true,
            icon: 'g-time-series',
            cat: 'ANALYTICS',
            catIcon: '',
            contextOrder: 100,
            order: 2
        },
        {
            title: `${t('taskRunFlow')}`,
            type: 'flow',
            onlyBucket: false,
            icon: 'g-run-flow',
            cat: 'DATAPREP',
            catIcon: '',
            contextOrder: 100,
            showOnContextMenu: true,
            order: 1
        },
        {
            title: `${t('taskMaps')}`,
            hidden: true,
            type: 'maps',
            onlyBucket: true,
            icon: 'g-map',
            cat: 'DELIVERY',
            showOnContextMenu: true,
            catIcon: '',
            contextOrder: 100,
            order: 3
        },
        // {
        //     title: `${t('taskInsights')}`,
        //     type: 'insights',
        //     onlyBucket: true,
        //     icon: 'g-insights',
        //     cat: 'DELIVERY',
        //     showOnContextMenu: true,
        //     catIcon: '',
        //     contextOrder: 100,
        //     order: 3
        // },
        {
            title: `${t('taskScoreCard')}`,
            type: 'scorecard',
            hidden: true,
            onlyBucket: true,
            icon: 'g-scorecard',
            cat: 'DELIVERY',
            showOnContextMenu: true,
            catIcon: '',
            contextOrder: 100,
            order: 3
        },
        {
            title: `${t('taskApi')}`,
            type: 'api',
            onlyBucket: true,
            icon: 'g-api',
            cat: 'DELIVERY',
            catIcon: '',
            showOnContextMenu: true,
            contextOrder: 100,
            order: 3
        },
        {
            title: `${t('taskRest')}`,
            type: 'rest',
            onlyBucket: false,
            icon: 'g-rest',
            cat: 'DATAPREP',
            catIcon: '',
            showOnContextMenu: true,
            contextOrder: 100,
            order: 1
        },
        {
            title: `${t('taskRestSms')}`,
            type: 'restSms',
            onlyBucket: true,
            icon: 'g-sms',
            showOnContextMenu: true,
            cat: 'DELIVERY',
            catIcon: '',
            contextOrder: 100,
            order: 3,
            hidden: true,
        },
        {
            title: `${t('taskWhatsapp')}`,
            type: 'whatsapp',
            onlyBucket: true,
            icon: 'g-whatsapp',
            cat: 'DELIVERY',
            showOnContextMenu: true,
            catIcon: '',
            contextOrder: 100,
            order: 3,
            hidden: true,
        },
        {
            title: `${t('taskMail')}`,
            type: 'mail',
            hidden: true,
            onlyBucket: true,
            icon: 'g-mail',
            showOnContextMenu: true,
            cat: 'DELIVERY',
            catIcon: '',
            contextOrder: 100,
            order: 3
        },
        {
            title: `${t('taskParamToTable')}`,
            type: 'paramToTable',
            onlyBucket: false,
            icon: 'g-param-to-table',
            cat: 'DATAPREP',
            catIcon: '',
            contextOrder: 100,
            showOnContextMenu: true,
            order: 1
        },
        {
            title: `${t('taskTableToParam')}`,
            type: 'tableToParam',
            onlyBucket: true,
            icon: 'g-table-to-param',
            cat: 'DATAPREP',
            showOnContextMenu: true,
            catIcon: '',
            contextOrder: 100,
            order: 1
        },
        {
            title: `${t('taskUserMirror')}`,
            type: 'userMirror',
            onlyBucket: false,
            icon: 'g-users',
            cat: 'DATAPREP',
            catIcon: '',
            contextOrder: 100,
            showOnContextMenu: true,
            order: 1
        },
        {
            title: `${t('taskCsvWeb')}`,
            type: 'csvUrl',
            onlyBucket: false,
            icon: 'g-csv-web',
            cat: 'DATAPREP',
            catIcon: '',
            contextOrder: 100,
            showOnContextMenu: true,
            order: 1
        },
        {
            title: `${t('taskLocalCsvFolder')}`,
            type: 'localCsv',
            onlyBucket: false,
            icon: 'g-csv-web',
            cat: 'DATAPREP',
            catIcon: '',
            contextOrder: 100,
            showOnContextMenu: true,
            order: 1
        },
        {
            title: `${t('taskGoogleSpreadsheet')}`,
            type: 'googleSpreadsheet',
            onlyBucket: false,
            icon: 'g-google-sheets',
            cat: 'DATAPREP',
            catIcon: '',
            contextOrder: 100,
            showOnContextMenu: true,
            order: 1
        },
        {
            title: `${t('taskPython')}`,
            type: 'python',
            onlyBucket: false,
            icon: 'python',
            iconAttribute: 'icon',
            hidden: false,
            cat: 'ANALYTICS',
            catIcon: '',
            contextOrder: 100,
            showOnContextMenu: true,
            order: 2
        }
    ]
}
