@TOKEN = Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJ1c2VyOjEiLCJuYW1lIjoiIiwiZW1haWwiOiJjb250YWN0QGdhaW8uaW8iLCJsYW5nIjoiZW4tVVMiLCJ0b2tlbiI6IiIsInRhZ3MiOiJbXSIsIm9wdGlvbnMiOiJ7XCJhcHBWaWV3VHlwZVwiOlwiZ3JpZFwiLFwiZmF2b3JBcHBzXCI6W1wiYXBwOjE2OVwiLFwiYXBwOjEzNTlcIixcImFwcDoxMzQ4XCIsXCJhcHA6MTM1MFwiXSxcInJlY2VudEFwcHNcIjpbXCJhcHA6MTY5XCJdfSIsInJvbGUiOiJhZG1pbiIsInN0YXR1cyI6ImFjdGl2ZSIsInR3b0ZhY3RvcktleSI6IiIsInR3b0ZhY3RvclNpZ25lZCI6IiIsInR3b0ZhY3RvclN0YXR1cyI6IiIsInByb2ZpbGVJZCI6IiIsImNyZWF0ZWRCeSI6IiIsIm1vZGlmaWVkQnkiOiJ1c2VyOjEiLCJjcmVhdGVkQXQiOiIyMDI0LTAxLTA5IDE2OjE2OjI5IiwidXBkYXRlZEF0IjoiMjAyNC0wMi0xNSAxNToyMToyNyJ9.aNSFX7ZDoW5R37I2kOzZEOXbWrg91qNJs20QFRJTlf4

POST http://localhost:3000/api/task/run-all
Authorization: {{TOKEN}}
Content-Type: application/json

{
  "from": "studio",
  "meta": {
    "appId": "app:1353",
    "flowId": "MqmYRnQa"
  },
  "params": [
    {
      "paramName": "customer_number",
      "paramValue": "test_number"
    }
  ],
  "tasks": [
    {
      "id": "xhhxHbXr",
      "type": "userMirror",
      "appId": "app:1353",
      "label": "FlatTable",
      "client": "clickhouse",
      "repoId": "repo:sdor4y5q2idat9spsbij",
      "fields": [ "name", "email"],
      "created": false,
      "profile": {
        "createdAt": "2024-03-01 10:44:12",
        "createdBy": 1,
        "updatedAt": "2024-03-01 10:44:12",
        "updatedBy": 1
      },
      "position": { "x": 658.0521465379272, "y": 136.0005276209571 },
      "userType": "userAll",
      "sourceType": "bucket",
      "resultTable": "fasdf",
      "bucketClient": "clickhouse",
      "databaseName": "bucket_1353"}
  ]
}
